# Header
menu:
  Home: /
  Archives: /archives

# SubNav
subnav:
  github: "https://github.com/lostleaf"
  linkedin: "https://www.linkedin.com/in/qinglin-li-29b23364"
  facebook: "https://www.facebook.com/lostleafmeow"
  weibo: "http://weibo.com/lostleaf9361"
  rss: "#"
  zhihu: "https://www.zhihu.com/people/lostleaf"
  douban: "https://www.douban.com/people/58601345/"
  #mail: "#"
  #google: "#"
  twitter: "https://twitter.com/L0STLEAF"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: '/img/avatar.jpg'
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: false
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
# friends:
#   奥巴马的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: Machine Learning Enthusiast / Sci-Fi Fan / Programmer
